# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=600, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url_article', models.URLField(blank=True, null=True)),
                ('url_website', models.URLField(blank=True, null=True)),
                ('url_audio', models.URLField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
