# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waverly', '0004_podcast_url_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='url_page',
        ),
        migrations.AddField(
            model_name='podcast',
            name='url_podcast',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='url_article',
            field=models.URLField(default='www.cnn.com'),
            preserve_default=False,
        ),
    ]
