# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waverly', '0006_auto_20170619_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='podcast',
            name='authors',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='domain',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='status',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='podcast',
            name='text1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
