# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waverly', '0008_remove_podcast_url_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='url_audio',
            new_name='url_audio1',
        ),
        migrations.AddField(
            model_name='podcast',
            name='url_audio2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
