# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waverly', '0009_auto_20170622_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='url_podcast',
            field=models.SlugField(blank=True, max_length=600),
        ),
    ]
