# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waverly', '0010_auto_20170626_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
